//! T-07 (persistence half) / R-08 / B-09: saving, opening, autosave, recovery and relink.
//!
//! Writes `verification/B-09_persistence_table.md` and two files the owner can open:
//! `B-09_saved_after_edit.json` and the fixture it came from, so the difference between them
//! can be read directly.
//!
//! # Where the expected values come from
//!
//! Every expectation below is either read off a fixture in `Fixtures/projects/` by hand, or
//! taken from a numbered document and quoted at its check. Nothing is generated by running the
//! code under test. ADR-009: "Tests are built from independent fixtures, never from snapshots
//! of the implementation under test."
//!
//! The strongest check here is the first one. `Fixtures/projects/` holds five project files
//! that were written by hand before any persistence code existed. Opening one and saving it
//! again must reproduce the file **byte for byte**. That single equality covers key order,
//! indentation, number formatting, Unicode, and — because the fixtures contain records this
//! build does not model — every one of ADR-008's preservation promises at once. A build that
//! quietly dropped a field, reordered a key or rounded a number would fail it.
//!
//! # What is deliberately not tested here
//!
//! Migration between schema versions. Version 0 is the only version there has ever been, so
//! there is no older file to migrate and no honest test to write. Opening a *newer* file is
//! tested, because that case can happen.

use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};

use anime_compositor::command::Command;
use anime_compositor::diagnostics::DiagnosticId;
use anime_compositor::model::{Asset, Id, Project, Value};
use anime_compositor::persist::{self, Preserved, AUTOSAVE_SLOTS};

// ---------------------------------------------------------------------------------------
// Reporting
// ---------------------------------------------------------------------------------------

struct Row {
    check: String,
    expected: String,
    actual: String,
}

impl Row {
    fn pass(&self) -> bool {
        self.expected == self.actual
    }
}

#[derive(Default)]
struct Report {
    rows: Vec<Row>,
}

impl Report {
    fn check(&mut self, check: &str, expected: impl ToString, actual: impl ToString) {
        self.rows.push(Row {
            check: check.to_string(),
            expected: expected.to_string(),
            actual: actual.to_string(),
        });
    }
}

fn repo(rel: &str) -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join(rel)
}

fn fixture(name: &str) -> String {
    let path = repo(&format!("Fixtures/projects/{name}.json"));
    fs::read_to_string(&path).unwrap_or_else(|e| panic!("reading {}: {e}", path.display()))
}

/// A directory of our own under `target/`, so a test run never writes next to the fixtures.
fn scratch(name: &str) -> PathBuf {
    let dir = repo("target/b09-scratch").join(name);
    let _ = fs::remove_dir_all(&dir);
    fs::create_dir_all(&dir).expect("scratch directory");
    dir
}

/// The first line where two texts differ, so a failure names the place rather than dumping
/// two files.
fn first_difference(a: &str, b: &str) -> String {
    let (x, y): (Vec<&str>, Vec<&str>) = (a.lines().collect(), b.lines().collect());
    for i in 0..x.len().max(y.len()) {
        let (l, r) = (
            x.get(i).copied().unwrap_or("<end of file>"),
            y.get(i).copied().unwrap_or("<end of file>"),
        );
        if l != r {
            return format!("line {}: {l:?} became {r:?}", i + 1);
        }
    }
    "differs only in the trailing newline".to_string()
}

/// The diagnostic identifiers a load produced, in order, as one string.
fn warning_ids(warnings: &[anime_compositor::diagnostics::Diagnostic]) -> String {
    if warnings.is_empty() {
        return "none".to_string();
    }
    warnings
        .iter()
        .map(|w| w.id.as_str())
        .collect::<Vec<_>>()
        .join(", ")
}

/// What opening this text does: either the identifier of the error that refused it, or the
/// word `opens` followed by any warnings.
fn opening(text: &str) -> String {
    match persist::load_str(text) {
        Err(d) => d.id.as_str().to_string(),
        Ok(l) => format!("opens with {}", warning_ids(&l.warnings)),
    }
}

const FIXTURES: [&str; 5] = [
    "minimal_project",
    "cel_holds_project",
    "missing_media_project",
    "unicode_paths_project",
    "unknown_effect_project",
];

// ---------------------------------------------------------------------------------------
// The test
// ---------------------------------------------------------------------------------------

#[test]
fn b09_persistence() {
    let mut report = Report::default();

    // == 1. Round trip ======================================================================
    // ADR-008: the project document is "human-inspectable". A file a person wrote by hand and
    // a file this build wrote have to be the same file, or "inspectable" means nothing the
    // second time it is saved.
    for name in FIXTURES {
        let text = fixture(name);
        let loaded = match persist::load_str(&text) {
            Ok(l) => l,
            Err(d) => panic!("{name} did not open: {} — {}", d.message, d.detail),
        };
        let written = persist::to_json(loaded.document.project(), &loaded.preserved);
        report.check(
            &format!("{name}.json: opening it and saving it reproduces the file"),
            "identical",
            if written == text {
                "identical".to_string()
            } else {
                first_difference(&text, &written)
            },
        );
    }

    // == 2. Values read off the fixtures by hand ============================================
    // Read from `Fixtures/projects/cel_holds_project.json` with a text editor.
    let cel = persist::load_str(&fixture("cel_holds_project")).expect("cel_holds opens");
    let project = cel.document.project();
    report.check("cel_holds: project ID", "proj-cel-holds", &project.id);
    report.check("cel_holds: assets", 1, project.assets.len());
    report.check("cel_holds: compositions", 1, project.compositions.len());
    let comp = &project.compositions[0];
    report.check(
        "cel_holds: composition size",
        "1920x1080",
        format!("{}x{}", comp.width, comp.height),
    );
    report.check(
        "cel_holds: frame rate",
        "24/1",
        format!(
            "{}/{}",
            comp.frame_rate.numerator(),
            comp.frame_rate.denominator()
        ),
    );
    report.check("cel_holds: duration in frames", 5, comp.duration_frames);
    report.check("cel_holds: layers", 1, comp.layers_in_order().count());
    let layer = comp.layers_in_order().next().expect("one layer");
    report.check("cel_holds: layer name", "Cel", &layer.name);
    report.check(
        "cel_holds: layer in and out frames",
        "0..5",
        format!("{}..{}", layer.in_frame, layer.out_frame),
    );
    report.check(
        "cel_holds: the two exposure spans, as document 20 writes them",
        "0..2 draws 1; 2..5 draws 2",
        layer
            .exposure_spans
            .iter()
            .map(|s| {
                format!(
                    "{}..{} draws {}",
                    s.start_frame, s.end_frame_exclusive, s.drawing_number
                )
            })
            .collect::<Vec<_>>()
            .join("; "),
    );
    report.check(
        "cel_holds: the asset's two drawing files",
        "1=media/cel_0001.png, 2=media/cel_0002.png",
        project.assets[0]
            .frames
            .iter()
            .map(|(n, f)| format!("{n}={f}"))
            .collect::<Vec<_>>()
            .join(", "),
    );

    // D-22. The file says `"scale": { "base": [100, 100] }` and document 21 composes
    // `S(scale/100)`, so a layer at natural size is 1.0 in the model. If this read 100, every
    // layer would render a hundred times too large.
    report.check(
        "cel_holds: scale 100 in the file is the factor 1 in the model (D-22)",
        "(1, 1)",
        pair(layer.transform.scale.base()),
    );

    // Read from `Fixtures/projects/unicode_paths_project.json`. Two non-ASCII strings, one a
    // name and one a path, both of which have to survive byte for byte.
    let uni = persist::load_str(&fixture("unicode_paths_project")).expect("unicode opens");
    let asset = &uni.document.project().assets[0];
    report.check("unicode: asset name", "背景_日本語", &asset.name);
    report.check(
        "unicode: asset path",
        "media/背景/夜空.png",
        asset.path.clone().unwrap_or_default(),
    );
    report.check(
        "unicode: the file is written as UTF-8 text, not as escape sequences",
        true,
        persist::to_json(uni.document.project(), &uni.preserved).contains("背景_日本語"),
    );

    // == 3. Data this build does not model ==================================================
    // ADR-008: "Unknown additive data is preserved."
    //
    // `work_area` is in every fixture and in the schema, and nothing in this build reads it.
    // `opaque_unknown_data` is in the effect record of `unknown_effect_project.json` and is
    // not in the schema at all. Both have to come back out. This is not the same check as the
    // round trip above: here the project is *edited* first, which is when a naive
    // implementation would rebuild the document from the model and lose everything else.
    let mut fx =
        persist::load_str(&fixture("unknown_effect_project")).expect("unknown effect opens");
    let comp_id = fx.document.project().compositions[0].id.clone();
    let layer_id = fx.document.project().compositions[0]
        .layers_in_order()
        .next()
        .expect("one layer")
        .id
        .clone();
    fx.document
        .apply(Command::RenameLayer {
            composition: comp_id.clone(),
            layer_id: layer_id.clone(),
            name: "Cel renamed".to_string(),
        })
        .expect("rename applies");
    let edited = persist::to_json(fx.document.project(), &fx.preserved);
    report.check(
        "after an edit: the new layer name is written",
        true,
        edited.contains("\"name\": \"Cel renamed\""),
    );
    report.check(
        "after an edit: the unknown vendor data in the effect survives",
        true,
        edited.contains("\"opaque_unknown_data\"") && edited.contains("\"keep_me\": true"),
    );
    report.check(
        "after an edit: the effect record this build cannot run survives",
        true,
        edited.contains("\"vendor.future.effect\"") && edited.contains("\"strength\": 0.5"),
    );
    report.check(
        "after an edit: work_area, which nothing in this build reads, survives",
        true,
        edited.contains("\"work_area\""),
    );
    // The edit changed one line and nothing else. Counting is the check: an implementation
    // that rewrote the document from the model would differ in many more places.
    let original = fixture("unknown_effect_project");
    let changed = original
        .lines()
        .zip(edited.lines())
        .filter(|(a, b)| a != b)
        .count();
    report.check(
        "after an edit: exactly one line of the file differs",
        1,
        changed,
    );
    report.check(
        "after an edit: the file is still the same length",
        original.lines().count(),
        edited.lines().count(),
    );

    // == 4. Files that must not open ========================================================
    // Document 07: "Newer unsupported major versions open read-only or fail clearly." This
    // build has no read-only mode, so it fails clearly.
    let newer =
        fixture("minimal_project").replace("\"schema_version\": 0", "\"schema_version\": 1");
    report.check(
        "a project saved by a newer version is refused by name (document 07)",
        "PROJECT_SCHEMA_NEWER",
        opening(&newer),
    );

    // Document 07: "Parse with size/depth limits, validate IDs and references."
    for (what, text) in [
        (
            "text that is not JSON at all",
            "this is not a project".to_string(),
        ),
        (
            "a composition zero pixels wide",
            fixture("minimal_project").replace("\"width\": 1920", "\"width\": 0"),
        ),
        (
            "a composition of zero frames",
            fixture("minimal_project").replace("\"duration_frames\": 24", "\"duration_frames\": 0"),
        ),
        (
            "a non-square pixel aspect ratio, which G1 does not support",
            fixture("minimal_project")
                .replace("\"pixel_aspect_ratio\": 1", "\"pixel_aspect_ratio\": 2"),
        ),
        (
            "a blend mode this build does not have",
            fixture("cel_holds_project").replace(
                "\"blend_mode\": \"normal\"",
                "\"blend_mode\": \"vivid-light\"",
            ),
        ),
        (
            "a colour working space other than the one ADR-002 fixes",
            fixture("minimal_project").replace(
                "\"working_space\": \"linear-srgb\"",
                "\"working_space\": \"display-p3\"",
            ),
        ),
        (
            "a layer whose out frame is before its in frame",
            fixture("cel_holds_project").replace("\"out_frame\": 5", "\"out_frame\": -1"),
        ),
        (
            "a layer naming an asset the project does not have",
            fixture("cel_holds_project").replace(
                "\"asset_id\": \"asset-cel\"",
                "\"asset_id\": \"asset-gone\"",
            ),
        ),
        (
            "a layer order naming a layer that is not there",
            fixture("cel_holds_project")
                .replace("\"layer-cel\"\n      ],", "\"layer-ghost\"\n      ],"),
        ),
        (
            "overlapping exposure spans, which document 20 forbids",
            fixture("cel_holds_project").replace(
                "\"start_frame\": 2,\n              \"end_frame_exclusive\": 5",
                "\"start_frame\": 1,\n              \"end_frame_exclusive\": 5",
            ),
        ),
        (
            "a keyframe interpolation mode that does not exist",
            fixture("cel_holds_project").replace(
                "\"keyframes\": []",
                "\"keyframes\": [{\"frame\": 0, \"value\": 1, \"interp\": \"bezier\"}]",
            ),
        ),
        (
            "a missing required field",
            fixture("cel_holds_project").replace("\"locked\": false,\n", ""),
        ),
    ] {
        report.check(
            &format!("{what} is refused"),
            "PROJECT_SCHEMA_INVALID",
            opening(&text),
        );
    }

    // The refusal has to say *where*, or the person holding a file that will not open has
    // nowhere to look. Document 28 requires "actionable detail".
    let bad_width = fixture("minimal_project").replace("\"width\": 1920", "\"width\": 0");
    let detail = match persist::load_str(&bad_width) {
        Err(d) => d.detail,
        Ok(_) => panic!("a composition zero pixels wide must not open"),
    };
    report.check(
        "the refusal names the place in the file",
        true,
        detail.contains("/compositions/0"),
    );

    // FX-MATTE-001, document 25: "A→B and B→A matte references must be rejected."
    let cycle = two_layer_matte_cycle();
    report.check(
        "FX-MATTE-001: two layers used as each other's matte",
        "MATTE_CYCLE",
        opening(&cycle),
    );

    // == 5. Files that open, with something to say ==========================================
    report.check(
        "an effect this build cannot run is a warning, not a refusal",
        "opens with EFFECT_UNSUPPORTED",
        opening(&fixture("unknown_effect_project")),
    );
    // D-24. Masks are parked by R-04 in document 23 and document 28 has no identifier for a
    // structurally valid record of a parked feature.
    let masked = fixture("cel_holds_project").replace(
        "\"mask\": null",
        "\"mask\": {\"inverted\": false, \"vertices\": [[0, 0], [10, 0], [10, 10]]}",
    );
    report.check(
        "a mask, which this build cannot draw, is a warning and the record is kept (D-24)",
        "opens with PROJECT_FEATURE_UNSUPPORTED",
        opening(&masked),
    );
    let mask_loaded = persist::load_str(&masked).expect("opens");
    report.check(
        "and the mask is still in the file after saving",
        true,
        persist::to_json(mask_loaded.document.project(), &mask_loaded.preserved)
            .contains("\"vertices\""),
    );

    let dangling = fixture("cel_holds_project").replace(
        "\"matte\": null",
        "\"matte\": {\"layer_id\": \"layer-nowhere\", \"mode\": \"alpha\"}",
    );
    report.check(
        "a matte pointing at a layer that is not there is a warning",
        "opens with MATTE_REFERENCE_MISSING",
        opening(&dangling),
    );
    let dangling_loaded = persist::load_str(&dangling).expect("opens");
    report.check(
        "and the broken matte reference is preserved rather than cleared (document 28)",
        true,
        persist::to_json(
            dangling_loaded.document.project(),
            &dangling_loaded.preserved,
        )
        .contains("layer-nowhere"),
    );

    // MEDIA_MISSING needs a directory to look in, so it comes from `load`, not `load_str`.
    // `missing_media_project.json` names two files, one of which is called DOES_NOT_EXIST.
    let dir = scratch("media");
    fs::create_dir_all(dir.join("media")).expect("media dir");
    fs::write(dir.join("media/cel_0001.png"), b"not really a png").expect("write");
    let project_path = dir.join("shot.json");
    fs::write(&project_path, fixture("missing_media_project")).expect("write project");
    let with_media = persist::load(&project_path).expect("opens");
    report.check(
        "a project naming a file that is not on disk warns and still opens",
        "opens with MEDIA_MISSING",
        format!("opens with {}", warning_ids(&with_media.warnings)),
    );
    report.check(
        "the warning names the file that is missing, not the one that is there",
        true,
        with_media.warnings[0]
            .detail
            .contains("DOES_NOT_EXIST_0002.png")
            && !with_media.warnings[0].detail.contains("media/cel_0001.png"),
    );
    report.check(
        "the missing file's reference is kept in the project (document 28)",
        true,
        persist::to_json(with_media.document.project(), &with_media.preserved)
            .contains("DOES_NOT_EXIST_0002.png"),
    );

    // == 6. Saving ==========================================================================
    // ADR-008: "Writes go to a temporary sibling file, are flushed and closed, validated where
    // practical, then atomically replaced."
    let dir = scratch("save");
    let path = dir.join("shot.json");
    let mut loaded = persist::load_str(&fixture("cel_holds_project")).expect("opens");
    report.check(
        "a project just opened is not dirty",
        false,
        loaded.document.is_dirty(),
    );
    let outcome = persist::save(&path, &mut loaded.document, &loaded.preserved);
    report.check(
        "saving an unchanged project succeeds",
        "saved",
        match &outcome {
            Ok(()) => "saved".to_string(),
            Err(d) => format!("{}: {}", d.id.as_str(), d.detail),
        },
    );
    outcome.expect("the rest of this section needs a file on disk");
    report.check(
        "saving writes the same bytes the fixture holds",
        "identical",
        {
            let written = fs::read_to_string(&path).expect("read back");
            if written == fixture("cel_holds_project") {
                "identical".to_string()
            } else {
                first_difference(&fixture("cel_holds_project"), &written)
            }
        },
    );
    report.check(
        "no temporary file is left beside the project",
        0,
        fs::read_dir(&dir)
            .expect("list")
            .filter(|e| {
                e.as_ref()
                    .map(|e| e.file_name().to_string_lossy().contains(".tmp"))
                    .unwrap_or(false)
            })
            .count(),
    );

    // Document 26: "Saving does not create an undo item."
    let undo_before = loaded.document.undo_depth();
    loaded
        .document
        .apply(Command::RenameLayer {
            composition: Id::new("comp-main"),
            layer_id: Id::new("layer-cel"),
            name: "Cel two".to_string(),
        })
        .expect("rename");
    report.check(
        "editing makes the document dirty",
        true,
        loaded.document.is_dirty(),
    );
    persist::save(&path, &mut loaded.document, &loaded.preserved).expect("saves again");
    report.check(
        "saving clears dirty (document 26)",
        false,
        loaded.document.is_dirty(),
    );
    report.check(
        "saving does not create an undo item (document 26)",
        undo_before + 1,
        loaded.document.undo_depth(),
    );

    // FX-IO-001 and FX-IO-002, document 25: an interrupted replacement retains the last valid
    // project, and a write failure reports PROJECT_SAVE_FAILED without truncating it.
    let good = fs::read_to_string(&path).expect("the good save");
    loaded
        .document
        .apply(Command::RenameLayer {
            composition: Id::new("comp-main"),
            layer_id: Id::new("layer-cel"),
            name: "Cel three".to_string(),
        })
        .expect("rename");
    let failure = persist::save_limited(&path, &mut loaded.document, &loaded.preserved, Some(120))
        .expect_err("the injected disk-full must fail the save");
    report.check(
        "FX-IO-002: a write that runs out of room reports the right thing",
        "PROJECT_SAVE_FAILED",
        failure.id.as_str(),
    );
    report.check(
        "FX-IO-001: and the project on disk is still the last one that saved, byte for byte",
        "identical",
        {
            let after = fs::read_to_string(&path).expect("read back");
            if after == good {
                "identical".to_string()
            } else {
                first_difference(&good, &after)
            }
        },
    );
    report.check(
        "after a failed save the changes are still unsaved, so nothing is silently lost",
        true,
        loaded.document.is_dirty(),
    );
    report.check(
        "the half-written temporary file is cleaned up",
        0,
        fs::read_dir(&dir)
            .expect("list")
            .filter(|e| {
                e.as_ref()
                    .map(|e| e.file_name().to_string_lossy().contains(".tmp"))
                    .unwrap_or(false)
            })
            .count(),
    );
    report.check(
        "the failure tells the person their work is still open",
        true,
        failure
            .remediation
            .as_deref()
            .unwrap_or_default()
            .contains("still open"),
    );

    // == 7. Autosave and recovery ===========================================================
    // Document 07: "Autosaves use separate recovery files and must not overwrite the last
    // manual save", retaining "five rotating snapshots".
    let dir = scratch("autosave");
    let path = dir.join("shot.json");
    let mut loaded = persist::load_str(&fixture("cel_holds_project")).expect("opens");
    persist::save(&path, &mut loaded.document, &loaded.preserved).expect("manual save");
    let manual = fs::read_to_string(&path).expect("read");

    loaded
        .document
        .apply(Command::RenameLayer {
            composition: Id::new("comp-main"),
            layer_id: Id::new("layer-cel"),
            name: "Edited but not saved".to_string(),
        })
        .expect("rename");
    let mut slots = Vec::new();
    for _ in 0..AUTOSAVE_SLOTS {
        // The rotation picks the oldest slot, and file timestamps on Windows are coarse
        // enough that two writes in the same millisecond tie. Waiting is the honest way to
        // make the ordering observable rather than assumed.
        std::thread::sleep(std::time::Duration::from_millis(20));
        slots
            .push(persist::autosave(&path, &loaded.document, &loaded.preserved).expect("autosave"));
    }
    report.check(
        "the first five autosaves use five different files",
        AUTOSAVE_SLOTS,
        slots
            .iter()
            .collect::<std::collections::BTreeSet<_>>()
            .len(),
    );
    report.check(
        "autosave does not touch the manual save (document 07)",
        "identical",
        {
            let now = fs::read_to_string(&path).expect("read");
            if now == manual {
                "identical".to_string()
            } else {
                first_difference(&manual, &now)
            }
        },
    );
    report.check(
        "autosave does not clear the dirty flag (document 26)",
        true,
        loaded.document.is_dirty(),
    );
    std::thread::sleep(std::time::Duration::from_millis(20));
    let sixth = persist::autosave(&path, &loaded.document, &loaded.preserved).expect("autosave");
    report.check(
        "the sixth autosave reuses the oldest of the five slots rather than making a sixth",
        slots[0].display().to_string(),
        sixth.display().to_string(),
    );
    report.check(
        "there are five recovery snapshots, not six",
        AUTOSAVE_SLOTS,
        persist::recovery_candidates(&path).len(),
    );
    let candidates = persist::recovery_candidates(&path);
    report.check(
        "the newest recovery snapshot is offered first",
        sixth.display().to_string(),
        candidates[0].path.display().to_string(),
    );
    let offer = persist::recovery_diagnostic(&candidates).expect("there are candidates");
    report.check(
        "and the offer is information, not an error (document 28)",
        "PROJECT_RECOVERY_AVAILABLE / Info",
        format!("{} / {:?}", offer.id.as_str(), offer.severity),
    );
    report.check(
        "a recovery snapshot is a complete project that opens on its own",
        "opens with none",
        opening(&fs::read_to_string(&candidates[0].path).expect("read snapshot")),
    );
    report.check(
        "and it holds the unsaved edit the manual save does not",
        true,
        fs::read_to_string(&candidates[0].path)
            .expect("read")
            .contains("Edited but not saved")
            && !manual.contains("Edited but not saved"),
    );
    report.check(
        "with nothing to recover, nothing is offered",
        true,
        persist::recovery_diagnostic(&[]).is_none(),
    );

    // == 8. Reopening =======================================================================
    // Document 26, required test: "undo/redo after project reopen is empty."
    let dir = scratch("reopen");
    let path = dir.join("shot.json");
    let mut loaded = persist::load_str(&fixture("cel_holds_project")).expect("opens");
    for name in ["one", "two", "three"] {
        loaded
            .document
            .apply(Command::RenameLayer {
                composition: Id::new("comp-main"),
                layer_id: Id::new("layer-cel"),
                name: name.to_string(),
            })
            .expect("rename");
    }
    loaded.document.undo().expect("one undo");
    report.check(
        "before saving: three edits made, one undone",
        "2 undo, 1 redo",
        format!(
            "{} undo, {} redo",
            loaded.document.undo_depth(),
            loaded.document.redo_depth()
        ),
    );
    persist::save(&path, &mut loaded.document, &loaded.preserved).expect("save");
    let reopened = persist::load(&path).expect("reopen");
    report.check(
        "undo after reopening a project is empty (document 26)",
        "0 undo, 0 redo",
        format!(
            "{} undo, {} redo",
            reopened.document.undo_depth(),
            reopened.document.redo_depth()
        ),
    );
    report.check(
        "a reopened project is not dirty",
        false,
        reopened.document.is_dirty(),
    );
    report.check(
        "and it holds the layer name that was saved, not the one that was undone",
        "two",
        reopened.document.project().compositions[0]
            .layers_in_order()
            .next()
            .expect("a layer")
            .name
            .clone(),
    );

    // == 9. Relink ==========================================================================
    // Document 07: relink "searches only user-selected locations" and "preserves layer IDs and
    // effects". Document 02: "Undo restores the prior reference."
    //
    // The chosen files are four real PNGs from the reference shot, handed over the way a file
    // dialog would hand them over. Nothing here scans a directory.
    // `Fixtures/reference_shot/layer2` holds twenty-four 1920x1080 drawings numbered 000 to
    // 023. The first four are taken, the way a person would shift-click four thumbnails.
    let shot = repo("Fixtures/reference_shot/layer2");
    let mut chosen: Vec<PathBuf> = fs::read_dir(&shot)
        .expect("reference shot layer2")
        .filter_map(|e| e.ok().map(|e| e.path()))
        .filter(|p| p.extension().map(|e| e == "png").unwrap_or(false))
        .collect();
    chosen.sort();
    chosen.truncate(4);
    report.check("four drawings were chosen for the relink", 4, chosen.len());

    let mut loaded = persist::load_str(&fixture("missing_media_project")).expect("opens");
    let before = loaded.document.project().assets[0].clone();
    let layers_before = layer_summary(loaded.document.project());
    let candidate = persist::relink_candidate(
        loaded.document.project(),
        &Id::new("asset-cel"),
        &chosen,
        &repo("Fixtures/reference_shot"),
    )
    .expect("candidate");
    // Document 07: "Show candidate sequence, dimensions, range and interpretation before
    // relink." The point of the preview is that a wrong folder is visible before it is applied.
    report.check(
        "the relink preview shows the frame range that was chosen",
        "0..3",
        candidate
            .range
            .map(|(a, b)| format!("{a}..{b}"))
            .unwrap_or_else(|| "none".to_string()),
    );
    report.check(
        "the relink preview shows the drawing size",
        "1920x1080",
        format!("{}x{}", candidate.width, candidate.height),
    );
    report.check(
        "the relink preview keeps the interpretation the project already recorded",
        format!("{:?}", before.interpretation),
        format!("{:?}", candidate.interpretation),
    );
    report.check(
        "nothing is changed by asking for a preview",
        true,
        loaded.document.project().assets[0] == before,
    );

    loaded
        .document
        .apply(persist::relink_command(&candidate))
        .expect("relink applies");
    report.check(
        "after relinking, the asset points at the chosen drawings",
        "layer2/layer2_000.png",
        loaded.document.project().assets[0]
            .frames
            .values()
            .next()
            .cloned()
            .unwrap_or_default(),
    );
    report.check(
        "after relinking, every layer is untouched (document 07)",
        layers_before.clone(),
        layer_summary(loaded.document.project()),
    );
    loaded.document.undo().expect("undo the relink");
    report.check(
        "undo restores the prior reference (document 02)",
        format!("{:?}", before.frames),
        format!("{:?}", loaded.document.project().assets[0].frames),
    );
    report.check(
        "and undo leaves the layers alone too",
        layers_before,
        layer_summary(loaded.document.project()),
    );
    report.check(
        "relinking media that is not in the project is refused",
        "COMMAND_TARGET_MISSING",
        match persist::relink_candidate(
            loaded.document.project(),
            &Id::new("asset-not-here"),
            &chosen,
            &repo("Fixtures/reference_shot"),
        ) {
            Err(d) => d.id.as_str(),
            Ok(_) => panic!("relinking an asset that is not in the project must be refused"),
        },
    );

    // == 10. A project made here, with nothing preserved ====================================
    // The other direction: a project that was never a file has no preserved data, and must
    // still write a file that opens.
    let mut fresh = Project::new(Id::new("proj-fresh"));
    fresh
        .assets
        .push(Asset::still(Id::new("a1"), "Background", "media/bg.png"));
    let text = persist::to_json(&fresh, &Preserved::none());
    report.check(
        "a project created in the application saves to a file that opens",
        "opens with none",
        opening(&text),
    );
    report.check("and that file round-trips too", "identical", {
        let again = persist::load_str(&text).expect("opens");
        let twice = persist::to_json(again.document.project(), &again.preserved);
        if twice == text {
            "identical".to_string()
        } else {
            first_difference(&text, &twice)
        }
    });

    // -- Artifacts ---------------------------------------------------------------------------
    fs::write(repo("verification/B-09_saved_after_edit.json"), &edited).expect("write artifact");
    write_report(&report);

    let failed: Vec<&Row> = report.rows.iter().filter(|r| !r.pass()).collect();
    assert!(
        failed.is_empty(),
        "{} of {} checks failed, first: {} — expected {:?}, got {:?}",
        failed.len(),
        report.rows.len(),
        failed[0].check,
        failed[0].expected,
        failed[0].actual
    );
}

/// A vec2 property value written the way the project file writes it, so the table reads like
/// the file rather than like a Rust value.
fn pair(value: Value) -> String {
    match value {
        Value::Vec2(x, y) => format!("({x}, {y})"),
        Value::Scalar(n) => format!("{n}"),
    }
}

/// A layer's identity and everything a relink must not touch, as one comparable string.
fn layer_summary(project: &Project) -> String {
    project
        .compositions
        .iter()
        .flat_map(|c| c.layers_in_order())
        .map(|l| {
            format!(
                "{}:{}:{}:{}..{}",
                l.id, l.name, l.asset_id, l.in_frame, l.out_frame
            )
        })
        .collect::<Vec<_>>()
        .join(" | ")
}

/// FX-MATTE-001: A uses B as its matte and B uses A as its matte.
fn two_layer_matte_cycle() -> String {
    let one = fixture("cel_holds_project");
    // Take the single layer out of the fixture, make two of it, and point each at the other.
    let start = one
        .find("        {\n          \"id\": \"layer-cel\"")
        .expect("the layer");
    let end = one
        .rfind("        }\n      ]")
        .expect("the end of the layer")
        + "        }".len();
    let layer = &one[start..end];
    let a = layer.replace("\"layer-cel\"", "\"layer-a\"").replace(
        "\"matte\": null",
        "\"matte\": {\"layer_id\": \"layer-b\", \"mode\": \"alpha\"}",
    );
    let b = layer.replace("\"layer-cel\"", "\"layer-b\"").replace(
        "\"matte\": null",
        "\"matte\": {\"layer_id\": \"layer-a\", \"mode\": \"alpha\"}",
    );
    let mut out = String::new();
    out.push_str(&one[..start]);
    out.push_str(&a);
    out.push_str(",\n");
    out.push_str(&b);
    out.push_str(&one[end..]);
    out.replace(
        "\"layer_order\": [\n        \"layer-cel\"\n      ],",
        "\"layer_order\": [\n        \"layer-a\",\n        \"layer-b\"\n      ],",
    )
}

fn write_report(report: &Report) {
    let passed = report.rows.iter().filter(|r| r.pass()).count();
    let mut out = String::new();
    out.push_str(&format!(
        "# B-09 — saving, opening, autosave, recovery and relink\n\n\
         **{passed} of {} checks passed.**\n\n\
         Generated by `tests/b09_persistence.rs`. Covers requirement R-08 and the persistence \
         half of test T-07, the persistence fixtures FX-IO-001, FX-IO-002 and FX-MATTE-001 in \
         document 25, and the last of document 26's eight required tests, \"undo/redo after \
         project reopen is empty\".\n\n\
         ## What to look at first\n\n\
         The five rows at the top of the table are the important ones. `Fixtures/projects/` \
         holds five project files that were written by hand, before any of this code existed. \
         Each row opens one of them and saves it again, and requires the result to be the same \
         file **byte for byte**.\n\n\
         That one equality is worth more than the rest of the table together. Passing it means \
         nothing was dropped, nothing was reordered, no number was rounded, no accented or \
         Japanese character was mangled, and the records this build cannot use — an effect from \
         a vendor that does not exist, a `work_area` nothing reads, a blob called \
         `opaque_unknown_data` — all came back out exactly as they went in. Failing it names \
         the first line that differs.\n\n\
         ## The other file to open\n\n\
         `B-09_saved_after_edit.json` is `Fixtures/projects/unknown_effect_project.json` \
         opened, its one layer renamed, and saved. Open the two side by side. Exactly one line \
         should differ: the layer's name. Everything else, including the effect this build \
         cannot run and the vendor data inside it, should be untouched. If more than one line \
         differs, saving is rewriting parts of the project it was not asked to change.\n\n\
         ## Checks\n\n| Check | Expected | Actual | Result |\n|---|---|---|---|\n",
        report.rows.len(),
    ));
    for r in &report.rows {
        out.push_str(&format!(
            "| {} | `{}` | `{}` | {} |\n",
            r.check,
            r.expected,
            r.actual,
            if r.pass() { "pass" } else { "**FAIL**" }
        ));
    }
    fs::write(repo("verification/B-09_persistence_table.md"), out).expect("write report");
}

/// Autosave slot numbering is part of the contract with whoever cleans these files up, so it
/// is stated here rather than left to whatever the implementation happens to do.
#[test]
fn autosave_files_sit_beside_the_project_and_are_named_for_their_slot() {
    let project = Path::new("shots/scene_04.json");
    let names: Vec<String> = (0..AUTOSAVE_SLOTS)
        .map(|n| {
            persist::autosave_path(project, n)
                .file_name()
                .expect("a name")
                .to_string_lossy()
                .into_owned()
        })
        .collect();
    assert_eq!(
        names,
        [
            "scene_04.autosave-0.json",
            "scene_04.autosave-1.json",
            "scene_04.autosave-2.json",
            "scene_04.autosave-3.json",
            "scene_04.autosave-4.json",
        ]
    );
    assert_eq!(
        persist::autosave_path(project, 0).parent(),
        project.parent(),
        "a recovery file must be beside the project, not somewhere nobody looks"
    );
}

/// Every identifier this module can produce is either in document 28's catalogue or is a
/// registered proposal to add one. Nothing invents an identifier silently.
#[test]
fn every_diagnostic_this_module_raises_is_accounted_for() {
    let catalogued = [
        DiagnosticId::ProjectSchemaNewer,
        DiagnosticId::ProjectSchemaInvalid,
        DiagnosticId::ProjectSaveFailed,
        DiagnosticId::ProjectRecoveryAvailable,
        DiagnosticId::MediaMissing,
        DiagnosticId::EffectUnsupported,
        DiagnosticId::MatteReferenceMissing,
        DiagnosticId::MatteCycle,
    ];
    for id in catalogued {
        assert!(id.in_catalog(), "{} should be in document 28", id.as_str());
    }
    assert!(
        !DiagnosticId::ProjectFeatureUnsupported.in_catalog(),
        "PROJECT_FEATURE_UNSUPPORTED is proposed as D-24 and is not in document 28 yet; when \
         the owner adds it, add it to the catalogue and delete this assertion"
    );
}

/// The schema version this build writes is the one the schema file itself declares. Two
/// numbers that must agree, kept honest by comparing them rather than by remembering.
#[test]
fn the_written_schema_version_matches_the_schema_file() {
    let schema = fs::read_to_string(repo("Schemas/project-v0.schema.json")).expect("the schema");
    let value: BTreeMap<String, serde_json::Value> =
        serde_json::from_str(&schema).expect("the schema is JSON");
    let declared = value["properties"]["schema_version"]["const"]
        .as_i64()
        .expect("schema_version has a const");
    assert_eq!(declared, persist::SCHEMA_VERSION);
}
