//! B-21b, D-72: a drawing in another format is the same picture as its PNG twin.
//!
//! Walks FX-FMT-001 to 010 from `Fixtures/formats/expected_formats.json`. Each file is read by
//! `media::decode`, as the importer and the renderer read it, and compared with its twin, which
//! is read by the PNG reader the build has always had. The files and the twins were written by
//! Pillow, not by the library the build reads them with.
//!
//! Writes `verification/B-21b_formats_table.md`.

use std::fs;
use std::path::{Path, PathBuf};

use anime_compositor::diagnostics::DiagnosticId;
use anime_compositor::media;

fn repo(rel: &str) -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join(rel)
}

#[test]
fn every_format_is_the_same_picture_as_its_png_twin() {
    let expected: serde_json::Value =
        serde_json::from_str(&fs::read_to_string(repo("Fixtures/formats/expected_formats.json")).unwrap())
            .unwrap();
    let mut out = String::from(
        "# B-21b: the new drawing formats against their PNG twins (D-72)\n\n\
         Generated by `cargo test --test b21b_formats`. The allowed difference is in steps of \
         255: 0 means every value must be identical; 3 is for JPEG and lossy WebP, where two \
         correct decoders may round differently.\n\n\
         | Fixture | What it is | Size read (expected) | Largest difference (allowed) | Imports | Matches |\n\
         | --- | --- | --- | --- | --- | --- |\n",
    );
    let (mut checks, mut passed) = (0, 0);
    for n in 1..=10 {
        let id = format!("FX-FMT-{n:03}");
        let case = &expected["cases"][&id];
        let file = repo(&format!("Fixtures/formats/{}", case["file"].as_str().unwrap()));
        let twin = repo(&format!("Fixtures/formats/{}", case["same_picture_as"].as_str().unwrap()));
        let allowed = case["tolerance_of_255"].as_f64().unwrap();

        let (size, worst) = match (media::decode(&file), media::decode(&twin)) {
            (Ok(built), Ok(twin)) => {
                let worst = if built.data().len() == twin.data().len() {
                    built.data().iter().zip(twin.data()).map(|(a, b)| ((a - b).abs() * 255.0).round() as f64).fold(0.0, f64::max)
                } else {
                    f64::INFINITY
                };
                ((built.width() as u64, built.height() as u64), worst)
            }
            (built, twin) => panic!("{id}: {:?} / {:?}", built.err(), twin.err()),
        };
        // The importer's own road: the file is accepted as a drawing with nothing to report.
        // A sequence is numbered, so the fixture is copied to a numbered name first.
        let numbered = std::env::temp_dir().join(format!(
            "b21b_{n}_001.{}",
            file.extension().unwrap().to_string_lossy()
        ));
        fs::copy(&file, &numbered).unwrap();
        let imported = media::import_sequence(&[numbered]);
        let imports = imported.asset.is_some() && imported.diagnostics.is_empty();

        let want = (case["width"].as_u64().unwrap(), case["height"].as_u64().unwrap());
        let ok = size == want && worst <= allowed && imports;
        checks += 1;
        passed += ok as usize;
        out.push_str(&format!(
            "| {id} | {} | {}x{} ({}x{}) | {worst} ({allowed}) | {} | {} |\n",
            case["says"].as_str().unwrap(), size.0, size.1, want.0, want.1,
            if imports { "yes" } else { "**NO**" },
            if ok { "yes" } else { "**NO**" },
        ));
    }

    // D-72: a file the reader cannot read is the existing diagnostic, no new one.
    let broken = std::env::temp_dir().join("b21b_not_a_picture.tga");
    fs::write(&broken, b"this is not a picture").unwrap();
    let refused = media::decode(&broken).err().map(|d| d.id);
    let ok = refused == Some(DiagnosticId::MediaDecodeFailed);
    checks += 1;
    passed += ok as usize;
    out.push_str(&format!(
        "\n| Check | The build's answer | Matches |\n| --- | --- | --- |\n\
         | A .tga file that is not a picture is refused with MEDIA_DECODE_FAILED | {refused:?} | {} |\n\
         \n**{passed} of {checks} match.**\n",
        if ok { "yes" } else { "**NO**" },
    ));
    fs::write(repo("verification/B-21b_formats_table.md"), out).unwrap();
    assert_eq!(passed, checks, "see verification/B-21b_formats_table.md");
}
