//! B-21c, D-72: GIF and animated PNG out.
//!
//! Walks FX-FMT-020 to 023, the GIF delays, from `Fixtures/formats/expected_formats.json`, then
//! exports frames 6 to 13 of the reference shot (`verification/B-08a_project.json`) three ways - a PNG sequence, a GIF and an
//! animated PNG - and reads the two animated files back with their own decoders.
//!
//! Writes `verification/B-21c_films_table.md`, and leaves the two files in
//! `verification/B-21c films/` for the owner to open in a browser.

use std::fs;
use std::path::{Path, PathBuf};
use std::sync::atomic::AtomicBool;

use anime_compositor::export::{
    export_sequence, ExportRequest, ExportStatus, MissingSource, OutputFormat,
};
use anime_compositor::film_out::{gif_delay, Film};
use anime_compositor::model::Id;
use anime_compositor::time::FrameRate;
use anime_compositor::{media, persist, OutputAlpha, OutputDepth};

fn repo(rel: &str) -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join(rel)
}

#[derive(Default)]
struct Table {
    out: String,
    checks: usize,
    passed: usize,
}

impl Table {
    fn row(&mut self, what: &str, expected: impl ToString, built: impl ToString) {
        let (expected, built) = (expected.to_string(), built.to_string());
        self.checks += 1;
        self.passed += (expected == built) as usize;
        let verdict = if expected == built { "yes" } else { "**NO**" };
        self.out
            .push_str(&format!("| {what} | {expected} | {built} | {verdict} |\n"));
    }
}

fn list(delays: &[u16]) -> String {
    delays.iter().map(u16::to_string).collect::<Vec<_>>().join(" ")
}

#[test]
fn a_gif_and_an_animated_png_hold_every_frame_for_the_right_time() {
    let mut t = Table::default();
    t.out.push_str(
        "# B-21c: GIF and animated PNG out (D-72)\n\n\
         Generated by `cargo test --test b21c_films`. The two files it reads back are in \
         `verification/B-21c films/`; open them in a browser.\n\n\
         | Check | Expected | The build's answer | Matches |\n| --- | --- | --- | --- |\n",
    );

    // ---- FX-FMT-020 to 023: the delays ---------------------------------------------------------
    let expected: serde_json::Value = serde_json::from_str(
        &fs::read_to_string(repo("Fixtures/formats/expected_formats.json")).unwrap(),
    )
    .unwrap();
    for n in 20..=23 {
        let id = format!("FX-FMT-{n:03}");
        let case = &expected["cases"][&id];
        let rate = FrameRate::new(
            case["frame_rate"][0].as_u64().unwrap() as u32,
            case["frame_rate"][1].as_u64().unwrap() as u32,
        )
        .unwrap();
        let want: Vec<u16> = case["delays_hundredths"]
            .as_array()
            .unwrap()
            .iter()
            .map(|d| d.as_u64().unwrap() as u16)
            .collect();
        let built: Vec<u16> = (0..case["frames"].as_u64().unwrap())
            .map(|i| gif_delay(i, rate))
            .collect();
        t.row(&format!("{id}: {}", case["says"].as_str().unwrap()), list(&want), list(&built));
        t.row(
            &format!("{id}: the delays add up to, in hundredths"),
            case["total_hundredths"].as_u64().unwrap(),
            built.iter().map(|d| *d as u64).sum::<u64>(),
        );
    }

    // ---- the files -----------------------------------------------------------------------------
    let source = repo("verification/B-08a_project.json");
    let loaded = persist::load(&source).unwrap_or_else(|d| panic!("{}", d.message));
    let project = loaded.document.project().clone();
    let root = repo("Fixtures/reference_shot");
    let out = repo("verification/B-21c films");
    let _ = fs::remove_dir_all(&out);
    fs::create_dir_all(&out).unwrap();
    let frames_dir = std::env::temp_dir().join("b21c_frames");
    let _ = fs::remove_dir_all(&frames_dir);
    fs::create_dir_all(&frames_dir).unwrap();

    let request = |dir: &Path, naming: &str, format| ExportRequest {
        composition: Id::new("comp-reference-shot"),
        first_frame: 6,
        last_frame: 13,
        output_dir: dir.to_path_buf(),
        naming: naming.to_string(),
        depth: OutputDepth::Eight,
        alpha: OutputAlpha::Straight,
        tile_size: anime_compositor::compose::DEFAULT_TILE_SIZE,
        missing: MissingSource::Block,
        format,
        choices: Default::default(),
    };
    let go = |r: &ExportRequest| export_sequence(&project, &root, r, &AtomicBool::new(false));

    let sequence = go(&request(&frames_dir, "f_%04d.png", OutputFormat::Png));
    assert!(sequence.succeeded(), "the PNG sequence did not export: {:?}", sequence.diagnostics);

    // GIF
    let report = go(&request(&out, "reference_shot.gif", OutputFormat::Gif));
    t.row(
        "a GIF export of 8 frames writes one file and says it succeeded",
        "true, 1 file, 8 frames",
        format!("{}, {} file, {} frames", report.succeeded(), report.written.len(), report.frames_requested),
    );
    assert!(report.succeeded(), "the GIF did not export: {:?}", report.diagnostics);
    let mut options = gif::DecodeOptions::new();
    options.set_color_output(gif::ColorOutput::RGBA);
    let mut decoder = options.read_info(fs::File::open(out.join("reference_shot.gif")).unwrap()).unwrap();
    let size = format!("{}x{}", decoder.width(), decoder.height());
    let mut delays = Vec::new();
    let mut worst = 0i32;
    let (mut sum, mut count) = (0u64, 0u64);
    while let Some(frame) = decoder.read_next_frame().unwrap() {
        if delays.is_empty() {
            // The first frame against the first PNG: a palette of 256 cannot be exact, so this
            // is a measure, reported, and only held to "recognisably the same picture".
            let twin = media::decode(&sequence.written[0]).unwrap();
            for (a, b) in frame.buffer.iter().zip(twin.data()) {
                let d = (*a as i32 - (b * 255.0).round() as i32).abs();
                worst = worst.max(d);
                sum += d as u64;
                count += 1;
            }
        }
        delays.push(frame.delay);
    }
    t.row("the GIF is the composition's size", "1920x1080", size);
    t.row("the GIF holds 8 frames with the delays of 24 frames a second: 33 hundredths in all, so one frame takes 5", "4 4 4 4 4 5 4 4", list(&delays));
    // D-72 gives no number for how close 256 colours must come, so this bar is the test's own:
    // it catches a wrong picture (a swapped channel, a wrong frame), not a coarse palette. The
    // owner's eye on the file is the real check.
    let mean = sum as f64 / count as f64;
    t.row(
        "the GIF's first frame is the PNG frame to within 4 of 255 on average (256 colours cannot be exact)",
        true,
        mean <= 4.0,
    );
    t.out.push_str(&format!(
        "| (measured, not judged) the average difference, and the largest at any one value | - | {mean:.2} and {worst} of 255 | - |\n"
    ));

    // Animated PNG
    let report = go(&request(&out, "reference_shot_animated.png", OutputFormat::Apng));
    t.row(
        "an animated PNG export of 8 frames writes one file and says it succeeded",
        "true, 1 file, 8 frames",
        format!("{}, {} file, {} frames", report.succeeded(), report.written.len(), report.frames_requested),
    );
    let decoder = png::Decoder::new(std::io::BufReader::new(
        fs::File::open(out.join("reference_shot_animated.png")).unwrap(),
    ));
    let mut reader = decoder.read_info().unwrap();
    let control = reader.info().animation_control.expect("the file is animated");
    t.row("it says it holds 8 frames and plays for ever (0 plays means for ever)", "8 frames, 0 plays", format!("{} frames, {} plays", control.num_frames, control.num_plays));
    let mut same = 0;
    let mut delay = String::new();
    for written in &sequence.written {
        let mut raw = vec![0u8; reader.output_buffer_size().unwrap()];
        let info = reader.next_frame(&mut raw).unwrap();
        let fc = reader.info().frame_control.expect("every frame has its control");
        delay = format!("{}/{}", fc.delay_num, fc.delay_den);
        let twin = media::decode(written).unwrap();
        let exact = raw[..info.buffer_size()]
            .iter()
            .zip(twin.data())
            .all(|(a, b)| *a as i32 == (b * 255.0).round() as i32);
        same += exact as usize;
    }
    t.row("every frame lasts exactly the frame rate's denominator over its numerator", "1/24", delay);
    t.row("each of its 8 frames is value for value the exported PNG frame", 8, same);

    // ---- refusals and cancelling ----------------------------------------------------------------
    t.row(
        "an animated PNG takes 24000/1001, and refuses a rate with a number above 65535",
        "taken, refused",
        format!(
            "{}, {}",
            if Film::apng_refusal(FrameRate::new(24000, 1001).unwrap()).is_none() { "taken" } else { "refused" },
            if Film::apng_refusal(FrameRate::new(120000, 1001).unwrap()).is_some() { "refused" } else { "taken" },
        ),
    );
    let cancelled = export_sequence(
        &project,
        &root,
        &request(&frames_dir, "stopped.gif", OutputFormat::Gif),
        &AtomicBool::new(true),
    );
    t.row(
        "a cancelled GIF leaves no half-made file",
        "Cancelled, file there: false",
        format!("{:?}, file there: {}", cancelled.status, frames_dir.join("stopped.gif").exists()),
    );
    assert_eq!(cancelled.status, ExportStatus::Cancelled);

    t.out.push_str(&format!("\n**{} of {} match.**\n", t.passed, t.checks));
    fs::write(repo("verification/B-21c_films_table.md"), &t.out).unwrap();
    assert_eq!(t.passed, t.checks, "see verification/B-21c_films_table.md");
}
