//! B-21d, D-72 and D-30: MP4 out, through the encoder Windows carries.
//!
//! Walks FX-FMT-030 from `Fixtures/formats/expected_formats.json`: for each row a small film is
//! written at that frame rate and the file's own time numbers are read back out of its bytes.
//! Then 22 frames of the reference shot (`verification/B-08a_project.json`) is exported for the
//! owner to play, and the refusals are asked for.
//!
//! Writes `verification/B-21d_mp4_table.md` and `verification/B-21d film/reference_shot.mp4`.
#![cfg(windows)]

use std::fs;
use std::path::{Path, PathBuf};
use std::sync::atomic::AtomicBool;

use anime_compositor::export::{export_sequence, ExportRequest, MissingSource, OutputFormat};
use anime_compositor::model::Id;
use anime_compositor::mp4_out::{self, Mp4};
use anime_compositor::time::FrameRate;
use anime_compositor::{persist, OutputAlpha, OutputDepth};

fn repo(rel: &str) -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join(rel)
}

#[derive(Default)]
struct Table {
    out: String,
    checks: usize,
    passed: usize,
}

impl Table {
    fn row(&mut self, what: &str, expected: impl ToString, built: impl ToString) {
        let (expected, built) = (expected.to_string(), built.to_string());
        self.checks += 1;
        self.passed += (expected == built) as usize;
        let verdict = if expected == built { "yes" } else { "**NO**" };
        self.out
            .push_str(&format!("| {what} | {expected} | {built} | {verdict} |\n"));
    }
}

fn u32_at(bytes: &[u8], at: usize) -> u32 {
    u32::from_be_bytes(bytes[at..at + 4].try_into().unwrap())
}

/// The video track's time numbers, read out of the MP4's own boxes: `mdhd` holds the timescale
/// and the duration, `stts` holds how long each frame lasts as runs of (count, length).
///
/// ponytail: finds each box by the last place its four letters appear rather than walking the
/// box tree; the index is at the end of the file, after the pictures. Good for one track and no
/// sound, which is the only kind this build writes; walk the tree when there is a second track.
fn time_numbers(file: &Path) -> (u32, u64, Vec<(u32, u32)>, String) {
    let bytes = fs::read(file).unwrap();
    let find = |name: &[u8]| {
        bytes
            .windows(4)
            .rposition(|w| w == name)
            .unwrap_or_else(|| panic!("no {} box", String::from_utf8_lossy(name)))
            + 4
    };
    let mdhd = find(b"mdhd");
    let (timescale, duration) = if bytes[mdhd] == 1 {
        (
            u32_at(&bytes, mdhd + 20),
            u64::from_be_bytes(bytes[mdhd + 24..mdhd + 32].try_into().unwrap()),
        )
    } else {
        (u32_at(&bytes, mdhd + 12), u32_at(&bytes, mdhd + 16) as u64)
    };
    let stts = find(b"stts");
    let runs = (0..u32_at(&bytes, stts + 4) as usize)
        .map(|i| (u32_at(&bytes, stts + 8 + i * 8), u32_at(&bytes, stts + 12 + i * 8)))
        .collect();
    let codec = if bytes.windows(4).any(|w| w == b"avc1") { "H.264" } else { "not H.264" };
    (timescale, duration, runs, codec.to_string())
}

#[test]
fn an_mp4_counts_time_in_the_frame_rates_own_numbers() {
    let mut t = Table::default();
    t.out.push_str(
        "# B-21d: MP4 out (D-72, D-30)\n\n\
         Generated by `cargo test --test b21d_mp4`, on Windows, with the H.264 encoder Windows \
         carries. The numbers in \"the build's answer\" are read back out of the written files' \
         own bytes, not from the program's memory. The film to play is \
         `verification/B-21d film/reference_shot.mp4`.\n\n\
         | Check | Expected | The build's answer | Matches |\n| --- | --- | --- | --- |\n",
    );
    let tmp = std::env::temp_dir().join("b21d_mp4");
    let _ = fs::remove_dir_all(&tmp);
    fs::create_dir_all(&tmp).unwrap();

    // ---- FX-FMT-030 ----------------------------------------------------------------------------
    let expected: serde_json::Value = serde_json::from_str(
        &fs::read_to_string(repo("Fixtures/formats/expected_formats.json")).unwrap(),
    )
    .unwrap();
    for (i, case) in expected["cases"]["FX-FMT-030"]["rows"].as_array().unwrap().iter().enumerate() {
        let n = |key: &str| case[key].as_u64().unwrap();
        let (num, den) = (case["frame_rate"][0].as_u64().unwrap(), case["frame_rate"][1].as_u64().unwrap());
        let rate = FrameRate::new(num as u32, den as u32).unwrap();
        let file = tmp.join(format!("row{i}.mp4"));
        let (w, h) = (64usize, 64usize);
        let mut film = Mp4::create(&file, w, h, rate).unwrap_or_else(|e| panic!("{e}"));
        for f in 0..n("frames") {
            // A grey that climbs, so no two frames are the same picture.
            let frame: Vec<u8> = (0..w * h).flat_map(|_| [(f * 5) as u8, 128, 200, 255]).collect();
            film.push(&frame).unwrap_or_else(|e| panic!("{e}"));
        }
        film.finish().unwrap_or_else(|e| panic!("{e}"));
        let (timescale, duration, runs, codec) = time_numbers(&file);
        let frames: u32 = runs.iter().map(|r| r.0).sum();
        let lengths: Vec<String> = runs.iter().map(|r| r.1.to_string()).collect();
        t.row(
            &format!("FX-FMT-030, {num}/{den} frames a second, {} frames: the timescale, how long each frame lasts, the frames, the whole length, the codec", n("frames")),
            format!("{}, {}, {}, {}, H.264", n("timescale"), n("frame_duration"), n("frames"), n("duration")),
            format!("{timescale}, {}, {frames}, {duration}, {codec}", lengths.join(" and ")),
        );
    }

    // ---- B-21e: the same rows through ffmpeg, the road for macOS and Linux ------------------------
    // Run here on Windows because this is where the tests run; skipped, and said so, on a
    // machine with no ffmpeg.
    if std::process::Command::new("ffmpeg").arg("-version").output().is_ok() {
        for (i, case) in expected["cases"]["FX-FMT-030"]["rows"].as_array().unwrap().iter().enumerate() {
            let n = |key: &str| case[key].as_u64().unwrap();
            let (num, den) = (case["frame_rate"][0].as_u64().unwrap(), case["frame_rate"][1].as_u64().unwrap());
            let rate = FrameRate::new(num as u32, den as u32).unwrap();
            let file = tmp.join(format!("ffmpeg_row{i}.mp4"));
            let (w, h) = (64usize, 64usize);
            let mut film = mp4_out::through_ffmpeg::Mp4::create(&file, w, h, rate).unwrap_or_else(|e| panic!("{e}"));
            for f in 0..n("frames") {
                let frame: Vec<u8> = (0..w * h).flat_map(|_| [(f * 5) as u8, 128, 200, 255]).collect();
                film.push(&frame).unwrap_or_else(|e| panic!("{e}"));
            }
            film.finish().unwrap_or_else(|e| panic!("{e}"));
            let (timescale, duration, runs, codec) = time_numbers(&file);
            let frames: u32 = runs.iter().map(|r| r.0).sum();
            let lengths: Vec<String> = runs.iter().map(|r| r.1.to_string()).collect();
            t.row(
                &format!("B-21e, through ffmpeg: FX-FMT-030, {num}/{den} frames a second, {} frames", n("frames")),
                format!("{}, {}, {}, {}, H.264", n("timescale"), n("frame_duration"), n("frames"), n("duration")),
                format!("{timescale}, {}, {frames}, {duration}, {codec}", lengths.join(" and ")),
            );
        }
    } else {
        t.out.push_str("| B-21e, through ffmpeg | not run: this machine has no ffmpeg | | skipped |\n");
    }

    // ---- the colour ----------------------------------------------------------------------------
    // BT.709's published numbers for video's 16 to 235 range: the 100% colour bars.
    for (name, rgba, want) in [
        ("white", [255u8, 255, 255, 255], "235 128 128"),
        ("black", [0, 0, 0, 255], "16 128 128"),
        ("red", [255, 0, 0, 255], "63 102 240"),
        ("green", [0, 255, 0, 255], "173 42 26"),
        ("blue", [0, 0, 255, 255], "32 240 118"),
        ("white that is wholly see-through, which is black in a film", [255, 255, 255, 0], "16 128 128"),
    ] {
        let nv12 = mp4_out::nv12_bt709(&rgba.repeat(4), 2, 2);
        t.row(
            &format!("{name} becomes BT.709's brightness and two colour differences"),
            want,
            format!("{} {} {}", nv12[0], nv12[4], nv12[5]),
        );
    }

    // ---- the refusals --------------------------------------------------------------------------
    for (w, h, names) in [(1921, 1080, "its width, 1921, is odd"), (1920, 1079, "its height, 1079, is odd"), (1921, 1079, "its width, 1921, and its height, 1079, are odd")] {
        t.row(
            &format!("a {w}x{h} composition is refused, and the sentence names the odd side"),
            names,
            mp4_out::refusal(w, h)
                .and_then(|s| s.contains(names).then(|| names.to_string()))
                .unwrap_or_else(|| "not refused, or not named".into()),
        );
    }
    t.row("a 1920x1080 composition is not refused", "taken", if mp4_out::refusal(1920, 1080).is_none() { "taken" } else { "refused" });

    // ---- the film ------------------------------------------------------------------------------
    let source = repo("verification/B-08a_project.json");
    let loaded = persist::load(&source).unwrap_or_else(|d| panic!("{}", d.message));
    let project = loaded.document.project().clone();
    let out = repo("verification/B-21d film");
    let _ = fs::remove_dir_all(&out);
    fs::create_dir_all(&out).unwrap();
    let request = |dir: &Path| ExportRequest {
        composition: Id::new("comp-reference-shot"),
        first_frame: 16,
        last_frame: 37,
        output_dir: dir.to_path_buf(),
        naming: "reference_shot.mp4".to_string(),
        depth: OutputDepth::Eight,
        alpha: OutputAlpha::Straight,
        tile_size: anime_compositor::compose::DEFAULT_TILE_SIZE,
        missing: MissingSource::Block,
        format: OutputFormat::Mp4,
    };
    let root = repo("Fixtures/reference_shot");
    let report = export_sequence(&project, &root, &request(&out), &AtomicBool::new(false));
    fs::write(repo("verification/B-21d_mp4_table.md"), &t.out).unwrap();
    assert!(report.succeeded(), "the film did not export: {:?}", report.diagnostics);
    t.row(
        "frames 16 to 37 of the reference shot, the longest run with no missing drawing, go out as one file",
        "true, 1 file, 22 frames",
        format!("{}, {} file, {} frames", report.succeeded(), report.written.len(), report.frames_requested),
    );
    let (timescale, duration, runs, codec) = time_numbers(&out.join("reference_shot.mp4"));
    t.row(
        "that film: timescale, each frame, frames, whole length, codec",
        "24, 1, 22, 22, H.264",
        format!(
            "{timescale}, {}, {}, {duration}, {codec}",
            runs.iter().map(|r| r.1.to_string()).collect::<Vec<_>>().join(" and "),
            runs.iter().map(|r| r.0).sum::<u32>()
        ),
    );

    let cancelled = export_sequence(&project, &root, &request(&tmp), &AtomicBool::new(true));
    t.row(
        "a cancelled MP4 leaves no half-made file",
        "Cancelled, file there: false",
        format!("{:?}, file there: {}", cancelled.status, tmp.join("reference_shot.mp4").exists()),
    );

    t.out.push_str(&format!("\n**{} of {} match.**\n", t.passed, t.checks));
    fs::write(repo("verification/B-21d_mp4_table.md"), &t.out).unwrap();
    assert_eq!(t.passed, t.checks, "see verification/B-21d_mp4_table.md");
}
