//! B-22b, D-73: the export choices in the core. Three MP4 qualities, GIF dithering, and the MP4
//! that says what its colour is.
//!
//! Walks FX-FMT-040 to 060 (the dithering by D-73a's FX-FMT-053 to 055, which retired 050 to
//! 052) from `Fixtures/formats/expected_formats.json`, then exports the
//! reference shot (`verification/B-08a_project.json`) each way for the owner to look at.
//!
//! Writes `verification/B-22b_choices_table.md` and the films in `verification/B-22 films/`.
#![cfg(windows)]

use std::fs;
use std::path::{Path, PathBuf};
use std::sync::atomic::AtomicBool;

use anime_compositor::export::{
    export_sequence, ExportChoices, ExportRequest, MissingSource, OutputFormat,
};
use anime_compositor::film_out::dither_indices;
use anime_compositor::model::Id;
use anime_compositor::mp4_out::{self, Mp4Quality};
use anime_compositor::time::FrameRate;
use anime_compositor::{persist, OutputAlpha, OutputDepth};

fn repo(rel: &str) -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join(rel)
}

#[derive(Default)]
struct Table {
    out: String,
    checks: usize,
    passed: usize,
}

impl Table {
    fn row(&mut self, what: &str, expected: impl ToString, built: impl ToString) {
        let (expected, built) = (expected.to_string(), built.to_string());
        self.checks += 1;
        self.passed += (expected == built) as usize;
        let verdict = if expected == built { "yes" } else { "**NO**" };
        self.out
            .push_str(&format!("| {what} | {expected} | {built} | {verdict} |\n"));
    }
}

/// What the file's colour box says: primaries, transfer, matrix, full range.
///
/// ponytail: the last place the letters `colr` appear, as `b21d_mp4.rs` finds its boxes; one
/// track and no sound is the only kind of file this build writes.
fn colour_label(file: &Path) -> String {
    let bytes = fs::read(file).unwrap();
    let Some(at) = bytes.windows(8).rposition(|w| w == b"colrnclx") else {
        return "the file does not say".into();
    };
    let n = |i: usize| u16::from_be_bytes([bytes[at + 8 + i], bytes[at + 9 + i]]);
    format!("{}, {}, {}, full range: {}", n(0), n(2), n(4), bytes[at + 14] & 0x80 != 0)
}

fn small_film(file: &Path, ffmpeg: bool) {
    let rate = FrameRate::new(24, 1).unwrap();
    let frame: Vec<u8> = [40u8, 160, 90, 255].repeat(64 * 64);
    if ffmpeg {
        let mut film = mp4_out::through_ffmpeg::Mp4::create(file, 64, 64, rate, Mp4Quality::Standard).unwrap();
        (0..4).for_each(|_| film.push(&frame).unwrap());
        film.finish().unwrap();
    } else {
        let mut film = mp4_out::Mp4::create(file, 64, 64, rate, Mp4Quality::Standard).unwrap();
        (0..4).for_each(|_| film.push(&frame).unwrap());
        film.finish().unwrap();
    }
}

#[test]
fn the_export_choices_do_what_d73_says() {
    let mut t = Table::default();
    t.out.push_str(
        "# B-22b: the export choices in the core (D-73)\n\n\
         Generated by `cargo test --test b22b_choices`, on Windows. The films to look at are in \
         `verification/B-22 films/`.\n\n\
         | Check | Expected | The build's answer | Matches |\n| --- | --- | --- | --- |\n",
    );
    let expected: serde_json::Value = serde_json::from_str(
        &fs::read_to_string(repo("Fixtures/formats/expected_formats.json")).unwrap(),
    )
    .unwrap();
    let cases = &expected["cases"];
    let tmp = std::env::temp_dir().join("b22b_choices");
    let _ = fs::remove_dir_all(&tmp);
    fs::create_dir_all(&tmp).unwrap();

    // ---- FX-FMT-040 ----------------------------------------------------------------------------
    for row in cases["FX-FMT-040"]["rows"].as_array().unwrap() {
        let n = |v: &serde_json::Value| v.as_u64().unwrap();
        let (w, h) = (n(&row["size"][0]), n(&row["size"][1]));
        let (num, den) = (n(&row["frame_rate"][0]), n(&row["frame_rate"][1]));
        let level = row["level"].as_str().unwrap();
        let quality = match level {
            "preview" => Mp4Quality::Preview,
            "standard" => Mp4Quality::Standard,
            _ => Mp4Quality::High,
        };
        t.row(
            &format!("FX-FMT-040, {w}x{h} at {num}/{den}, {level}: bits a second asked of the encoder"),
            n(&row["bits_a_second"]),
            mp4_out::bitrate(w as usize, h as usize, FrameRate::new(num as u32, den as u32).unwrap(), quality),
        );
    }

    // ---- FX-FMT-053 to 055 (D-73a; 050 to 052 are retired) -------------------------------------
    for fx in ["FX-FMT-053", "FX-FMT-054", "FX-FMT-055"] {
        assert_eq!(cases[fx]["limit"], 16, "the build's limit is D-73a's");
        let case = &cases[fx];
        let bytes = |v: &serde_json::Value| -> Vec<u8> {
            v.as_array().unwrap().iter().map(|x| x.as_u64().unwrap() as u8).collect()
        };
        let rgba: Vec<u8> = case["pixels_rgba"].as_array().unwrap().iter().flat_map(bytes).collect();
        let palette: Vec<[u8; 3]> = case["palette_rgb"]
            .as_array()
            .unwrap()
            .iter()
            .map(|c| bytes(c).try_into().unwrap())
            .collect();
        let width = case["width"].as_u64().unwrap() as usize;
        let grid = |cells: Vec<Option<u64>>| {
            cells
                .chunks(width)
                .map(|r| r.iter().map(|c| c.map_or(".".into(), |c| c.to_string())).collect::<String>())
                .collect::<Vec<_>>()
                .join(" / ")
        };
        t.row(
            &format!("{fx}, dithered: {} Rows top to bottom, a dot is see-through", case["says"].as_str().unwrap()),
            grid(case["palette_index_or_null"].as_array().unwrap().iter().map(|v| v.as_u64()).collect()),
            grid(dither_indices(&rgba, width, &palette, None).into_iter().map(|p| p.map(u64::from)).collect()),
        );
    }

    // ---- FX-FMT-060 ----------------------------------------------------------------------------
    let label = &cases["FX-FMT-060"];
    let want = format!(
        "{}, {}, {}, full range: {}",
        label["colour_primaries"], label["transfer_characteristics"], label["matrix_coefficients"], label["full_range"]
    );
    small_film(&tmp.join("windows.mp4"), false);
    t.row("FX-FMT-060, the encoder Windows carries: primaries, transfer, matrix, range, read from the file", &want, colour_label(&tmp.join("windows.mp4")));
    if std::process::Command::new("ffmpeg").arg("-version").output().is_ok() {
        small_film(&tmp.join("ffmpeg.mp4"), true);
        t.row("FX-FMT-060, through ffmpeg (B-21e)", &want, colour_label(&tmp.join("ffmpeg.mp4")));
    } else {
        t.out.push_str("| FX-FMT-060, through ffmpeg | not run: this machine has no ffmpeg | | skipped |\n");
    }

    // ---- the films -----------------------------------------------------------------------------
    let loaded = persist::load(&repo("verification/B-08a_project.json")).unwrap_or_else(|d| panic!("{}", d.message));
    let project = loaded.document.project().clone();
    let root = repo("Fixtures/reference_shot");
    let out = repo("verification/B-22 films");
    let _ = fs::remove_dir_all(&out);
    fs::create_dir_all(&out).unwrap();
    let mut export = |name: &str, first, last, format, choices| {
        let request = ExportRequest {
            composition: Id::new("comp-reference-shot"),
            first_frame: first,
            last_frame: last,
            output_dir: out.clone(),
            naming: name.to_string(),
            depth: OutputDepth::Eight,
            alpha: OutputAlpha::Straight,
            tile_size: anime_compositor::compose::DEFAULT_TILE_SIZE,
            missing: MissingSource::Block,
            format,
            choices,
        };
        let report = export_sequence(&project, &root, &request, &AtomicBool::new(false));
        assert!(report.succeeded(), "{name} did not export: {:?}", report.diagnostics);
        fs::metadata(out.join(name)).unwrap().len()
    };
    let mut weighs = Vec::new();
    for (name, mp4_quality) in [("preview.mp4", Mp4Quality::Preview), ("standard.mp4", Mp4Quality::Standard), ("high.mp4", Mp4Quality::High)] {
        weighs.push(export(name, 16, 37, OutputFormat::Mp4, ExportChoices { mp4_quality, ..Default::default() }));
    }
    // No document sets a size: the encoder spends what the picture needs. That the three differ
    // in the right order is this test's own check that the choice reaches the encoder.
    t.row(
        &format!("22 frames of the reference shot at the three qualities weigh {} bytes; preview is the lightest and high the heaviest (the test's own check, no document sets a size)", weighs.iter().map(u64::to_string).collect::<Vec<_>>().join(", ")),
        true,
        weighs[0] < weighs[1] && weighs[1] < weighs[2],
    );
    t.row("the high film says its colour too", &want, colour_label(&out.join("high.mp4")));

    let plain = export("plain.gif", 6, 8, OutputFormat::Gif, ExportChoices::default());
    let dithered = export("dithered.gif", 6, 8, OutputFormat::Gif, ExportChoices { gif_dither: true, ..Default::default() });
    let frames = |name: &str| {
        let mut decoder = gif::DecodeOptions::new().read_info(fs::File::open(out.join(name)).unwrap()).unwrap();
        let mut n = 0;
        while decoder.read_next_frame().unwrap().is_some() {
            n += 1;
        }
        n
    };
    t.row(
        &format!("frames 6 to 8 as a GIF, plain ({plain} bytes) and dithered ({dithered} bytes): each reads back as 3 frames, and the two files are not the same"),
        "3, 3, different",
        format!("{}, {}, {}", frames("plain.gif"), frames("dithered.gif"), if fs::read(out.join("plain.gif")).unwrap() != fs::read(out.join("dithered.gif")).unwrap() { "different" } else { "the same" }),
    );

    t.out.push_str(&format!("\n**{} of {} match.**\n", t.passed, t.checks));
    fs::write(repo("verification/B-22b_choices_table.md"), &t.out).unwrap();
    assert_eq!(t.passed, t.checks, "see verification/B-22b_choices_table.md");
}
